### ISSUE TITLE
PEER TO PEER REVIEW MODULE 2 WEEK 3 DAY 2

### ISSUE THREAD

**Issue by clintonjosephs** [HAMMAS-SALEEM/ToDoList#6]
Hey @HAMMAS-SALEEM, Great work on your project. 

Project Highlights 👏🏻

✔️ No linter errors.
✔️ You used the correct Github Flow.
✔️ Professional README
✔️ Good commit messages
✔️ No console.log() or eval() left in the build

There are a few things that can be modified
- It would be nice to put the `header` outside the `section` tag in your [index.html](https://github.com/HAMMAS-SALEEM/ToDoList/blob/bbf7548f034add24134c74d68f24518d0092880f/src/index.html#L14-L16), so it follows HTML best practices
- Prefer using `forEach` to `for` loop this will make your loops more readable and less prone to errors [CRUD.JS](https://github.com/HAMMAS-SALEEM/ToDoList/blob/bbf7548f034add24134c74d68f24518d0092880f/src/CRUD.js#L21-L23)
- You have some comments in your build files, consider removing them so you do not have anything that is not needed in your project [Comments](https://github.com/HAMMAS-SALEEM/ToDoList/blob/bbf7548f034add24134c74d68f24518d0092880f/src/CRUD.js#L36-L43)
- Consider creating a class for your LocalStorage manipulation, this will help you avoid repetition the calls to save and get data from the [LocalStorage](https://github.com/HAMMAS-SALEEM/ToDoList/blob/bbf7548f034add24134c74d68f24518d0092880f/src/CRUD.js#L2-L30)
- Prefer implementing submitting to add and edit todo list with enter key on your project

Great Job man!

**Comment by aimemalaika** [comment]
Hey @HAMMAS-SALEEM, Great work on your project.
Project Highlights 👏🏻
✔️ No linter errors.
✔️ You used the correct Github Flow.
✔️ Professional README
✔️ Good commit messages
✔️ No console.log() or eval

- [ ] On line, [index.js#L41-L61](https://github.com/HAMMAS-SALEEM/ToDoList/blob/bbf7548f034add24134c74d68f24518d0092880f/src/index.js#L41-L61) use `submit` event instead of click as u are using a `form`
- [ ] Try to use classes and methods
- [ ] on line [CRUD.js#L33-L45](https://github.com/HAMMAS-SALEEM/ToDoList/blob/bbf7548f034add24134c74d68f24518d0092880f/src/CRUD.js#L33-L45) use a `submit` event because the `keyup` can send multiple useless request

**Comment by jaflih** [comment]
Good job @HAMMAS-SALEEM  👍 

Here are two suggestions to improve your project.

1/ You have a folder `assets` at the root of your project but all data must be in the `src` directory. So I recommend moving it.

2/ Concerning your code, you can sum this part of the code to be more maintainable, because here are few differents elements  : 

 output.innerHTML += `<li class="todos">
        <ul class="todos-01" >
        <li><input type="checkbox" id="check-${item.index}" class=" toDoItems"></li>
        <li><input type='text' value="${item.description}" class="toDoItems tdt inputs" id=${item.index} readOnly></input></li>
        </ul>
        <i class="fas fa-ellipsis-v"></i>
        <i class="fas fa-trash-alt" id="${item.index}"></i>
    </li>`;
    } else {
      output.innerHTML += `<li class="todos">
        <ul class="todos-01">
        <li><input type="checkbox" class=" toDoItems" id="check-${item.index}" **checked**></li>
        <li><input type='text' value="${item.description}" class="toDoItems tdt inputs **completed**" id="${item.index}" readOnly></input></li>
        </ul>
        <i class="fas fa-ellipsis-v"></i>
        <i class="fas fa-trash-alt" id="${item.index}"></i>
    </li>`;

 
[Line 52-58](https://github.com/HAMMAS-SALEEM/ToDoList/blob/bbf7548f034add24134c74d68f24518d0092880f/src/CRUD.js#L52-L58)
[Line 60 - 67](
https://github.com/HAMMAS-SALEEM/ToDoList/blob/bbf7548f034add24134c74d68f24518d0092880f/src/CRUD.js#L60-L67)

**Comment by HAMMAS-SALEEM** [comment]
Thanks for the feedback. I have implemented all changes you suggested.
Keep doing this again and again.
I will appreciate that. 👍
